### ISSUE TITLE
Unable to add window

### ISSUE THREAD

**Issue by GermanMontejo** [jaredrummler/MaterialSpinner#28]
Something weird is happening here. I have added the `MaterialSpinner` to a `PopupWindow`. The popup window shows the `MaterialSpinner` but when I touch it, the app force closes with this error:

```java
MaterialSpinner spinnerCategory = (MaterialSpinner) view.findViewById(R.id.spinner);
spinner.setItems("Jelly Bean", "KitKat", "Lollipop", "Marshmallow");
```

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@2493a9d is not valid; is your activity running?
  at android.view.ViewRootImpl.setView(ViewRootImpl.java:562)
  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)
  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
  at android.widget.PopupWindow.invokePopup(PopupWindow.java:1104)
  at android.widget.PopupWindow.showAtLocation(PopupWindow.java:933)
  at android.widget.PopupWindow.showAtLocation(PopupWindow.java:897)
  at com.jaredrummler.materialspinner.MaterialSpinner.expand(MaterialSpinner.java:404)
  at com.jaredrummler.materialspinner.MaterialSpinner.onTouchEvent(MaterialSpinner.java:199)
  at android.view.View.dispatchTouchEvent(View.java:8471)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
  at android.view.View.dispatchPointerEvent(View.java:8666)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
  at android.os.MessageQueue.nativePollOnce(Native Method)
  at android.os.MessageQueue.next(MessageQueue.java:143)
  at android.os.Looper.loop(Looper.java:122)
  at android.app.ActivityThread.main(ActivityThread.java:5258)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Note: I haven't added any listeners yet. I don't know why this is happening. The `MaterialSpinner` view is added in a layout and that layout is inflated and used by a `PopupWindow`.

**Comment by jaredrummler** [comment]
The `MaterialSpinner` uses a `PopupWindow` too. Maybe Android doesn't like a `PopupWindow` showing in another `PopupWindow`. This is a very old issue so I'm going to close this. If you still have issues comment and I will re-open. Apologies for the delayed reply.
